
- name: read project config {{ configfolder }}/project.json
  include_vars:
    dir: "{{ configfolder }}"
    files_matching: 'project'
    ignore_unknown_extensions: True
    extensions:
    - "json"
  register: result

- name: Debug - list of included config files
  debug:
    msg: "included: {{ item }}"
  loop: "{{ result.ansible_included_var_files }}"
  delegate_to: localhost

# {{ docker_config | to_yaml(indent=4) }}

- name: Debug - yaml of network config
  debug:
    msg: "{{ item.network | to_yaml }}"
  loop: "{{ projectdata.vms }}"
  delegate_to: localhost

